
export enum WalletStatus {
  INITIAL = "INITIAL",
  ENABLED = "ENABLED",
  INVERIFICATION = "INVERIFICATION",
  VERIFICATIONFAILED = "VERIFICATIONFAILED",
  SUSPENDED = "SUSPENDED",
}

export enum WalletType {
  CUSTOMER = "CUSTOMER",
  CHEF = "CHEF",
}
